### ISSUE TITLE
Trilha não encontrada na Universidade TOTVS

### ISSUE THREAD

**Issue by cirqueira-labs** [deboraconstantino/meus-pets-oficial#1]
Olá @deboraconstantino 
Não consegui encontrar a trilha "Aplicações PO-UI e serviços REST no Protheus" da Universidade TOTVS, embora eu tenha acesso aos demais treinamentos que existem na Universidade TOTVS.
Ela ainda está em desenvolvimento?
Obrigado

**Comment by deboraconstantino** [comment]
Olá @cirqueira-labs 
O curso está passando por algumas edições e logo estará disponível :)
