### ISSUE TITLE
A Trilha está aberta mas o Include está aberto para download já? Uns anos atrás não estava.

### ISSUE THREAD

**Issue by HorselessName** [deboraconstantino/meus-pets-oficial#2]
Olá,

Eu estou fazendo o curso aqui mas vi que uns anos atrás esse include que você usou no seu curso não estava disponibilizado.
A TOTVS já liberou pra deixar usar e baixar? Pq os que temos aqui não tem o `tlpp-core.th` na minha pasta dos Includes.

**Comment by deboraconstantino** [comment]
> Olá,
> 
> Eu estou fazendo o curso aqui mas vi que uns anos atrás esse include que você usou no seu curso não estava disponibilizado. A TOTVS já liberou pra deixar usar e baixar? Pq os que temos aqui não tem o `tlpp-core.th` na minha pasta dos Includes.

Bom dia!
Está disponível sim. Você pode extraí-lo conforme a documentação https://tdn.totvs.com/pages/viewpage.action?pageId=555860439

**Comment by HorselessName** [comment]
Legal! Deu certo, muito obrigado Debora! A documentação explicou certinho. Valeu.
